# Generated by Django 3.2.6 on 2021-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
